# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.proconip_pool_controller: debug

# Enable VSCode debugging
debugpy:
  start: true
  wait: true
